package bthd.borratuhuelladigital;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jesus
 */
public class NombreUsuario extends javax.swing.JFrame {

    /**
     * Creates new form NombreUsuario
     */
    public NombreUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        tfNombreUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnSiguiente5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(4, 36, 54));

        tfNombreUsuario.setBackground(new java.awt.Color(4, 48, 54));
        tfNombreUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Swis721 Cn BT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("Crea un nombre de usuario");

        btnSiguiente5.setBackground(new java.awt.Color(14, 94, 200));
        btnSiguiente5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSiguiente5.setForeground(new java.awt.Color(255, 255, 255));
        btnSiguiente5.setText("Siguiente");
        btnSiguiente5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguiente5ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre de usuario");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfNombreUsuario)
                    .addComponent(btnSiguiente5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSiguiente5)
                .addContainerGap(378, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguiente5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguiente5ActionPerformed
    String nombreUsuario = tfNombreUsuario.getText().trim();

    if (nombreUsuario.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "El nombre de usuario no puede estar vacío. Por favor, elige uno que siga las reglas de netiqueta.",
            "Error en Nombre de Usuario",
            javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    String mensajeReglas = """
        Antes de continuar, considera estas reglas para un nombre de usuario seguro y respetuoso:
        - No uses información personal (como tu nombre completo, fecha de nacimiento o dirección).
        - Evita nombres ofensivos, groseros o inapropiados.
        - Sé creativo, pero asegúrate de que sea fácil de recordar.
        - No uses contraseñas o información sensible como nombre de usuario.
        - Usa nombres que promuevan un ambiente positivo en línea.
    """;

    int opcion = javax.swing.JOptionPane.showConfirmDialog(this,
        mensajeReglas + "\n\n¿Cumple tu nombre de usuario con estas reglas?",
        "Conciencia sobre Nombre de Usuario",
        javax.swing.JOptionPane.YES_NO_OPTION,
        javax.swing.JOptionPane.QUESTION_MESSAGE);

    if (opcion == javax.swing.JOptionPane.NO_OPTION) {
        String mensajeRiesgos = """
            Riesgos al usar nombres inapropiados o personales:
            - Podrías comprometer tu privacidad y exponer información sensible.
            - Nombres ofensivos podrían llevar a restricciones o bloqueos en plataformas.
            - Podrías ser víctima de acoso o burlas por un nombre inapropiado.
            - Nombres que contienen datos sensibles aumentan tu vulnerabilidad al robo de identidad.
        """;
        javax.swing.JOptionPane.showMessageDialog(this,
            mensajeRiesgos + "\n\nPor favor, elige un nombre de usuario que sea seguro y apropiado.",
            "Advertencia de Privacidad",
            javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    int confirmacionFinal = javax.swing.JOptionPane.showConfirmDialog(this,
        "¿Estás seguro de que quieres usar este nombre de usuario: '" + nombreUsuario + "'?\n" +
        "Recuerda que el nombre de usuario es visible para todos los usuarios de la plataforma.",
        "Confirmación de Nombre de Usuario",
        javax.swing.JOptionPane.YES_NO_OPTION,
        javax.swing.JOptionPane.WARNING_MESSAGE);

    if (confirmacionFinal == javax.swing.JOptionPane.NO_OPTION) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Por favor, elige un nuevo nombre de usuario que cumpla con las reglas de netiqueta.",
            "Cambio de Nombre de Usuario",
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
        return;
    }

    TerminosYcondiciones pestana6 = new TerminosYcondiciones();
    pestana6.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_btnSiguiente5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NombreUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NombreUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NombreUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NombreUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NombreUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSiguiente5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tfNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
