package bthd.borratuhuelladigital;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jesus
 */
public class NOmbreDelUsuario extends javax.swing.JFrame {

    /**
     * Creates new form NOmbreDelUsuario
     */
    public NOmbreDelUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSiguiente4 = new javax.swing.JButton();
        tfNombreCompleto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(4, 36, 54));

        jLabel1.setFont(new java.awt.Font("Swis721 Cn BT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("¿Cómo te llamas?");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre completo");

        btnSiguiente4.setBackground(new java.awt.Color(14, 94, 200));
        btnSiguiente4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSiguiente4.setForeground(new java.awt.Color(255, 255, 255));
        btnSiguiente4.setText("Siguiente");
        btnSiguiente4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguiente4ActionPerformed(evt);
            }
        });

        tfNombreCompleto.setBackground(new java.awt.Color(4, 48, 54));
        tfNombreCompleto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfNombreCompleto.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfNombreCompleto)
                    .addComponent(btnSiguiente4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSiguiente4)
                .addContainerGap(378, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguiente4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguiente4ActionPerformed
    String nombreCompleto = tfNombreCompleto.getText().trim();

    if (nombreCompleto.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Por favor, proporciona tu nombre completo.", 
            "Campo Vacío", 
            javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    int confirmar = javax.swing.JOptionPane.showConfirmDialog(this, 
        "Proporcionar tu nombre real puede impactar tu huella digital.\n" +
        "Riesgos de usar tu nombre real en una plataforma digital:\n" +
        "- Es más fácil que te identifiquen en búsquedas en línea.\n" +
        "- Podrías ser objetivo de campañas de marketing personalizadas.\n" +
        "- Facilita la recopilación de datos por parte de terceros.\n\n" +
        "¿Deseas continuar?", 
        "Confirmación de Información", 
        javax.swing.JOptionPane.YES_NO_OPTION);

    if (confirmar == javax.swing.JOptionPane.NO_OPTION) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Tu nombre real puede ser utilizado para:\n" +
            "1. Crear perfiles detallados sobre ti en internet.\n" +
            "2. Relacionar otras cuentas o información que hayas compartido.\n" +
            "3. Acceder a datos sensibles en caso de vulnerabilidades de seguridad.\n\n" +
            "Para proteger tu privacidad, considera usar un alias o nombre menos identificable.", 
            "Riesgos de Proporcionar Nombre Real", 
            javax.swing.JOptionPane.INFORMATION_MESSAGE);

        int continuar = javax.swing.JOptionPane.showConfirmDialog(this, 
            "¿Aún deseas proporcionar tu nombre real?", 
            "Confirmación Final", 
            javax.swing.JOptionPane.YES_NO_OPTION);

        if (continuar == javax.swing.JOptionPane.NO_OPTION) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "El registro se ha cancelado. Reflexiona sobre los riesgos antes de continuar.", 
                "Registro Cancelado", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            System.exit(0);
        }
    }

    javax.swing.JOptionPane.showMessageDialog(this, 
        "Has decidido usar tu nombre real: " + nombreCompleto + 
        ".\nRecuerda proteger tu privacidad en todo momento.", 
        "Nombre Registrado", 
        javax.swing.JOptionPane.INFORMATION_MESSAGE);

    NombreUsuario pestana5 = new NombreUsuario();
    pestana5.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_btnSiguiente4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NOmbreDelUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NOmbreDelUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NOmbreDelUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NOmbreDelUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NOmbreDelUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSiguiente4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfNombreCompleto;
    // End of variables declaration//GEN-END:variables
}
